#ifndef HLS_SET_COLOUR_H
#define HLS_SET_COLOUR_H

#include <windef.h>
#include <winbase.h>
#include <apisetcconv.h>
#include <wincon.h>

#define SET_COLOUR_FOREGROUND_INTENSITY		FOREGROUND_INTENSITY
#define SET_COLOUR_FOREGROUND_WHITE			FOREGROUND_INTENSITY|FOREGROUND_RED	|FOREGROUND_GREEN	|FOREGROUND_BLUE
#define SET_COLOUR_FOREGROUND_RED			FOREGROUND_INTENSITY|FOREGROUND_RED
#define SET_COLOUR_FOREGROUND_GREEN			FOREGROUND_INTENSITY				|FOREGROUND_GREEN
#define SET_COLOUR_FOREGROUND_BLUE			FOREGROUND_INTENSITY									|FOREGROUND_BLUE
#define SET_COLOUR_FOREGROUND_YELLOW		FOREGROUND_INTENSITY|FOREGROUND_RED	|FOREGROUND_GREEN
#define SET_COLOUR_FOREGROUND_MAGENTA		FOREGROUND_INTENSITY|FOREGROUND_RED						|FOREGROUND_BLUE
#define SET_COLOUR_FOREGROUND_CYAN			FOREGROUND_INTENSITY				|FOREGROUND_GREEN	|FOREGROUND_BLUE

#define SET_COLOUR_BACKGROUND_INTENSITY		BACKGROUND_INTENSITY
#define SET_COLOUR_BACKGROUND_WHITE			BACKGROUND_INTENSITY|BACKGROUND_RED	|BACKGROUND_GREEN	|BACKGROUND_BLUE
#define SET_COLOUR_BACKGROUND_RED			BACKGROUND_INTENSITY|BACKGROUND_RED
#define SET_COLOUR_BACKGROUND_GREEN			BACKGROUND_INTENSITY				|BACKGROUND_GREEN
#define SET_COLOUR_BACKGROUND_BLUE			BACKGROUND_INTENSITY									|BACKGROUND_BLUE
#define SET_COLOUR_BACKGROUND_YELLOW		BACKGROUND_INTENSITY|BACKGROUND_RED	|BACKGROUND_GREEN
#define SET_COLOUR_BACKGROUND_MAGENTA		BACKGROUND_INTENSITY|BACKGROUND_RED						|BACKGROUND_BLUE
#define SET_COLOUR_BACKGROUND_CYAN			BACKGROUND_INTENSITY				|BACKGROUND_GREEN	|BACKGROUND_BLUE

#define SET_COLOUR_FOREGROUND_DEFAULT		FOREGROUND_INTENSITY
#define SET_COLOUR_BACKGROUND_DEFAULT		0

inline void set_colour(WORD set_colour=SET_COLOUR_FOREGROUND_DEFAULT|SET_COLOUR_BACKGROUND_DEFAULT)
{
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),set_colour);
	return;
}

#endif
//https://zhidao.baidu.com/question/161772478.html
